### ISSUE TITLE
Replacement to MediaStreamError

### ISSUE THREAD

**Issue by vasharma05** [basst314/ngx-webcam#130]
### What is this issue about?
This issue Is about the removal of `MediaStreamError` in typescript 4.4, as mentioned in https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029. Since the file path https://github.com/basst314/ngx-webcam/blob/master/src/app/modules/webcam/domain/webcam-init-error.ts#L3.

Do look into the issue asap.
Waiting for a reply.

Thanks!

**Comment by hisham** [comment]
+1. This comes up as an issue with Angular 13 now.

**Comment by Mds92** [comment]
The same problem

**Comment by ChrisLoes** [comment]
same problem. Does anybody has a solution? :/

**Comment by vdnprasad** [comment]
Still getting same problem even I've used typescript 4.4 onward and below are my application using angular cli version
![ng_version](https://user-images.githubusercontent.com/16150973/141294810-1e67677f-0bc6-4568-b7d5-477e8551775e.PNG)

**Comment by chriskinzel** [comment]
@ChrisLoes as a quick fix I added this to my typings.d.ts global types file.
```typescript
declare global {
  type MediaStreamError = Error;
}
```

**Comment by ChrisLoes** [comment]
already fixed with #134, should only be merged.

**Comment by alexrait** [comment]
> ```ts
> declare global {
>   type MediaStreamError = Error;
> }
> ```

For this to work, we need to add 
export {}
at the top.
But it solved it for now, thank you.

**Comment by KandarpRami174** [comment]
"MediaStreamError" change to "EndOfStreamError"

this is work for me

**Comment by beyondtheobservableuniverse** [comment]
> EndOfStreamError

How can i add this to Angular?

**Comment by beyondtheobservableuniverse** [comment]
> @ChrisLoes as a quick fix I added this to my typings.d.ts global types file.
> 
> ```ts
> declare global {
>   type MediaStreamError = Error;
> }
> ```

How can i add this to Angular?

**Comment by chriskinzel** [comment]
@beyondtheobservableuniverse create a file `typings.d.ts` under your Angular project `src` directory and paste into there. Make sure your tsconfig is set to automatically include .d.ts files.

**Comment by basst314** [comment]
This has been fixed in #134 and is part of version 0.4.1 of this library. Please update to the latest version.

**Comment by jbistis** [comment]
Does this 0.4.1 require a13?  If yes, is there a fix that does not require an upgrade to a13?  We are running 12.2.6 with 4.2.4.

**Comment by jbistis** [comment]
basst314, I upgraded to a13.1.2 with typescript 4.5.4 and ngx-webcam 0.4.1.   I am still getting the error Cannot find name 'MediaStreamError'. Did you mean 'EndOfStreamError'?  What can I do to fix this?

**Comment by KillianLu** [comment]
I think that was not fixed
